version: '3.8'

services:
  # Main application service
  app:
    build: .
    env_file:
      - .env
    image: ln-train-batch-app:latest 
    container_name: ln-train-batch-app
    volumes:
      - ./src:/app/src
      - ~/.aws:/root/.aws:ro
    ports:
      - "8000:8000"
    networks:
      - ln-train-batch-network
networks:
  ln-train-batch-network:
    driver: bridge
